### ISSUE TITLE
New styled component API

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#1126]
We want to migrate styled-jss to the latest react-version (hooks based) and at the same time make the API more familiar to everyone by implementing some of the emotions API.

## TODO
- [x] Initial effort #1094
- [ ] optimize perf
- [ ] docs
- [ ] add docs and links for the styled system
- [ ] Hook prefix in class name is pointless
- [ ] don't render additional static rule, when rule is a function 
- [ ] babel plugin to pass the component name to the class name
- [ ] warnings in dev mode for unsupported rules annoying when unsupported css is used by choice to target browsers which support it?
- [ ] jest serializer
- [ ] css function
- [ ] css prop

**Comment by caub** [comment]
I'd love styled-jss to be updated! looking forward to do the same as https://github.com/cssinjs/examples/blob/gh-pages/react-ssr/src/server.js#L3 with styled-jss (I plan to use it with preact btw)
