### ISSUE TITLE
Generated keyframe id 

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#346]
Currently keyframe id's we use in jss are global. The questions are:
1. Do we want to generate a keyframe id to avoid conflicts?
2. Do we want to allow user to define the keyframe id optionally and generate it by default?
3. How would user access generated keyframe id?

Currently user can generate keyframe id like this, but I assume it is not very user friendly:

```js
const identifier = Math.random()
export default {
  [`@keyframes ${identifier}`]: {
    from: {opacity: 0},
    to {opacity: 1}
  }
}
```

## Todo

```javascript
const sheet = jss.createStyleSheet({
  '@keyframes fadeIn': {
     from: {opacity: 0},
     to {opacity: 1}
  },
  button: {
    animationName: '$fadeIn',
  }
})

sheet.keyframes.fadeIn // @keyframes fadeIn-12378676134
```

- [x] generate id
- [x] register it in keyframes hash
- [x] docs
- [x] changelog
- [x] allow unscoped keyframes via global plugin
- [x] allow `animation` property?
- [x] if we could run ref replacer after jss-expand, we could also support `animation: {name}` syntax and we wouldn't have to support `animationName` if we could run it after camel case plugin
- [x] document inside of @global rule and global prefix
- [x] rename generateClassName

**Comment by giuseppeg** [comment]
> Do we want to generate a keyframe id to avoid conflicts?

I think so, users can make them global if they want #324

> Do we want to allow user to define the keyframe id optionally and generate it by default?

This would be a neat feature because often times animations are used only once. In fact I twitted [this same idea](https://twitter.com/giuseppegurgone/status/777862367183011840) once and made a [prototype](https://twitter.com/giuseppegurgone/status/777883190094618624)

**Comment by kof** [comment]
Good catch regarding #324, haven't thought about this particular case yet. Needs to be considiered!

**Comment by kof** [comment]
The question is though how would you access the generated keyframe id in other style sheets if you want to reuse the keyframes in different parts of the application.

**Comment by kof** [comment]
Also another question how to access it locally in the same sheet:

```js
const sheet = jss.createStyleSheet({
  '@keyframes fadeIn': {
    from: {opacity: 0},
    to {opacity: 1}
  },
  animationName: '$fadeIn',
  // or
  animation: '$fadeIn steps(4, end) 1s infinite'
})
```

**Comment by iamstarkov** [comment]
nice

**Comment by iamstarkov** [comment]
thanks

**Comment by kof** [comment]
Btw. if `@keyframes` is defined within a rule and has no animation name specified, we can simply generate one and define `animationName` property with this name automatically.

```js
const sheet = jss.createStyleSheet({
  button: {
    '@keyframes': {
      from: {opacity: 0},
      to {opacity: 1}
    }
    // Automatically added.
    animationName: 'keyframes-123456'
  }
})
```

**Comment by kof** [comment]
Another thing: if we automatically add a suffix to a keyframe name, we should create a keyframes hash same like for classes `sheet.keyframes.name`

**Comment by sergeysova** [comment]
What about keyframes API like in [styled-components](https://www.styled-components.com/docs/api#keyframes) for styled-jss?

```js
import styled, { keyframes } from 'styled-jss'

const opacityAnimation = keyframes({
  from: { opacity: 0 },
  to: { opacity: 1 },
})

const Block = styled('div')({
  backgroundColor: 'red',
  animation: `${opacityAnimation} infinite 2s linear`,
})
```

**Comment by damianobarbati** [comment]
@kof I was trying to convert this http://tobiasahlin.com/spinkit/ into JSS but I'm having no luck.

What am I doing wrong? My animation turns to be the following rule:
`animation: $stretchdelay 1.2s infinite ease-in-out` instead of being translated to the real class name.

```
import React from 'react';
import PropTypes from 'prop-types';
import injectSheet from 'react-jss';

@injectSheet(theme => ({
    spinner: {
        margin: [100, 'auto'],
        width: 50,
        height: 40,
        textAlign: 'center',
        fontSize: 10,

        '& > div': {
            backgroundColor: '#333',
            height: '100%',
            width: 6,
            display: 'inline-block',
            animation: '$stretchdelay 1.2s infinite ease-in-out',
        },
    },
    rect2: {
        animationDelay: -1.1,
    },
    rect3: {
        animationDelay: -1.0,
    },
    rect4: {
        animationDelay: -0.9,
    },
    rect5: {
        animationDelay: -0.8,
    },
    '@keyframes stretchdelay': {
        '0%, 40%, 100%': {
            transform: 'scaleY(0.4)',
        },
        '20%': {
            transform: 'scaleY(1.0)',
        },
    },
}))
export default class Loader extends React.PureComponent {
    static propTypes = {
        classes: PropTypes.object.isRequired,
    };

    render = () => {
        const { classes } = this.props;

        return (
            <div className={classes.spinner}>
                <div className={classes.rect1} />
                <div className={classes.rect2} />
                <div className={classes.rect3} />
                <div className={classes.rect4} />
                <div className={classes.rect5} />
            </div>
        );
    };
}
```

**Comment by kof** [comment]
@damianobarbati in such cases please use separate issues, this issue is not a support forum :) in your case I already see that you are using $stretchdelay for some reason, however there is no documentation to use $ prefix for animation names, this issue was never implemented.

Pls remove the question from here and repost if still required.

**Comment by damianobarbati** [comment]
Is this implemented? What is the current proper way to define keyframes?

**Comment by HenriBeck** [comment]
@damianobarbati it should be: `animation: stretchdelay 1.2s infinite ease-in-out`

We are currently not doing any particular transforms to the keyframes rule, which means you can use the name of the keyframe in your css.

**Comment by damianobarbati** [comment]
Thanks @HenriBeck, then I'll stick to not use $ references.

Sorry for the noise guys 😅

**Comment by HenriBeck** [comment]
@damianobarbati I wrote a small little package yesterday with a similar API as the styled components keyframe API

https://github.com/cssinjs/jss-keyframes

**Comment by HenriBeck** [comment]
@kof do you think it would make sense to move the package to the monorepo?

**Comment by kof** [comment]
We should have started with a CR first, I see a number of issues with this implementation, can you make a pr somewhere, so that I can review line by line?

**Comment by HenriBeck** [comment]
Implemented in #888

**Comment by kof** [comment]
Subscribe #795 for updates about release date.

**Comment by damianobarbati** [comment]
@kof @HenriBeck is there any official example on "how to use keyframes" with jss?

**Comment by kof** [comment]
@damianobarbati did you see it in the docs? https://cssinjs.org/jss-syntax?v=v10.0.0-alpha.10#keyframes-animation did it help?

**Comment by HenriBeck** [comment]
https://cssinjs.org/jss-syntax?v=v10.0.0-alpha.10#keyframes-animation

**Comment by damianobarbati** [comment]
Ops, I did a global search "keyframes" on the docs but I didn't open every section. My apologies 🙏🏻
