### ISSUE TITLE
Landing - final enhancements

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#393]
Original issue is #78.

Goal - one place for the entire project documentation. Easier learning and plugins discovery.

## Todo

- [x] Structure of the documentation for JSON Syntax + plugins - should be like a book
- [x] Remove loading indicator (no need for cdn content, its fast)
- [x] Link edit button to the view, not to the edit page
- [x] Register the app, use the token, rate limits without it are 60req/hour per IP.
- [x] Format all plugins docs syntax examples like the core
- [x] Make submenu expanded by default?
- [x] Versioning on every page
  - Select  with tags (latest by default)
  - Load selected version from github via tags
  - Save recent selected version per repository
- [x] Add analytics
- [x] Use markdown-it for parsing md
- [x] Rewrite links parser
- [x] pushState instead of hashes in the url
  - We could generate index.html files for each route based on configuration.
- [x] linkify normal URLs
- [x] Write an intro for  "Abstractions on top of JSS"
- [x] Router fixes
  - [x] Home should be always "/", right now there are 3 links which all render home
  - [x] First Level 1 navigation should have the same url as its parent
  - [x] Fix path to the js/css files from generated html files
  - [x] Fix local url links
  - [x] Handle local hash urls by jumping to the target
  - [x] Don't do full page reload on links
- [x] Add anchor to headlines line on github
- [x] Add id's to the headlines to be linked over hashes
- [x] Integrate playground?
- [x] Transition should be more material and go in both directions correctly
- [x] There should be no transition on first load
- [x] Move all baseStyles to the proper components
- [x] Move most media query selectors to one place
- [x] Rewrite dirty CSS parts
- [x] Why REM?
- [x] Use css-functions
- [x] Render SVGs with React, without xhr loading
- [x] Use jss-isolate
- [x] Do full SSR with rehydration
- [x] Integrate examples
  - [x] remove simple once
  - [x] update complex once
  - [x] link each of them via iframe
  - [x] make sure every example has a link to source in new window
- [ ] Maintainers team page (nice to have)

Design

- [x] Position of JSS inside of logo, both white and yellow is not quite as original one.
- [x] Any alternatives to the full screen animated logo?
- [x] h1 too big?
- [x] h3 should be smaller than h2?
- [x] h margins too big?
- [x] Edit button too big?
- [x] Navigation too big?
- [x] Subnavigation - bad ux with click on arrow and X
- [x] Navigation "->" too ugly
- [x] Lists margin is too big?
- [x] 3-rd level navigation not properly visualized/indented (jss-expand)
- [x] Mark external links in the navigation if we keep them that way.

**Comment by typical000** [comment]
Created 2 variations of design.

v1: https://dl.dropboxusercontent.com/u/7605560/jss/jss_v1.jpg
v2: https://dl.dropboxusercontent.com/u/7605560/jss/jss_v2.jpg

Common changes:
1. Fixed main JSS logo (top-left corner) to fit original design
2. Changed (decreased) heading sizes and all typography in general
3. Changed 'Roboto' font to 'Fira Sans' as more readable (by my opinion, of course)
4. Sidebar and subnavigation - made it more simplier.
    - Removed inutile separations that adds too much space between
    - Removed fold/unfold icon (->) now all list is unfolded by default
    - Third party navigation now is more distinctive - simply added left margin
5. Edit button made more smaller
6. Added version change widget (top-right corner of content)
7. Added mark to extenral links in menu (see here: https://dl.dropboxusercontent.com/u/7605560/jss/jss_v2.jpg)

V1 Changes:
1. Leaved main parallax scene as it was before. It SOOOO beatifull :D

V2 Changes:
1. Removed main, parallax scene. Replace inverted logo in top left corner with original one. No mouse-move animation, or very weak one.

@kof wdyt

**Comment by kof** [comment]
I like the new navigation, edit button and version selector. 
Relation between headers and font size feels not right (but maybe its just me). H1 with underscore? I think its  a problem, to easy to mix it up with a link. People will try to click on it.

**Comment by kof** [comment]
I am undecided regarding the logo (big one vs small one)

**Comment by typical000** [comment]
> H1 with underscore?
You're right. It was a bad idea. I'll remove underline on h1.

> I am undecided regarding the logo (big one vs small one)
Let's think few days about this. Because I'm not sure about logo too.
Anyway we can leave big logo because it's already done.

**Comment by kof** [comment]
Question: do you think we need a way to collaps parts navigation? What should happen when user clicks on a category like Home?

**Comment by kof** [comment]
Another thought: I realized that url's we build there should be well through thought, because we don't want them to change when people start linking to them.

**Comment by kof** [comment]
Going to rething the url schema.

**Comment by okonet** [comment]
I've just noticed the 2 design updates. The v2 is definitively a way to go here:

1. Let's remove all the lines from the content area. They only add visual noise. Use white space to align the content.
1. I feel like the version number selector should go to the left column just below the logo since it will define the context of the navigation, not just the page viewed.
1. I still feel the yellow background for the logo is "too much"
1. Can we try removing the dark background from the navigation and make it look more like the part of the content? Right now it stands out a lot but I don't think this is good.
1. The amount of stars and the link to GitHub are important but they are taking too much of the valuable place for returning visitors. They should probably go to the home page content.
1. Instead, I'd add a search field to filter quickly through the plugins.
1. I'm questioning the IA a bit. What is "JSON Syntax"? Why are same plugins in "JSON Syntax" and "Plugins" section? Examples below the plugins — it should be probably the part of the "Home" and "Home" should go away.
1. "Edit this page" — what's the purpose? Can this be made smaller and less distracting?

**Comment by kof** [comment]
> I feel like the version number selector should go to the left column just below the logo since it will define the context of the navigation, not just the page viewed.

Version selector is not for the entire documentation, because plugins come from different packages and have different versions. So the version thing is part of the content, not a global thing.

**Comment by kof** [comment]
> I'm questioning the IA a bit. What is "JSON Syntax"? Why are same plugins in "JSON Syntax" and "Plugins" section?

Changed that already, check out the structure here http://cssinjs.org/

The problem I was trying to solve is: some of the plugins extend the json syntax, some are not. I wanted to have  a JSON syntax thing readable in one go, without jumping from one place to another, basically for someone using jss + jss-preset-defaul, which I assume will be the majority.

**Comment by kof** [comment]
> "Edit this page" — what's the purpose? Can this be made smaller and less distracting?

The purpose is to make it easy to send a documentation fix, similar to gitbook and lots of others, I thought v2 makes it look ok, no?

**Comment by kof** [comment]
> I still feel the yellow background for the logo is "too much"

In the v2, yeah ...

**Comment by kof** [comment]
> The amount of stars and the link to GitHub are important but they are taking too much of the valuable place for returning visitors. They should probably go to the home page content.

Also amount of stars and github buttone lead to the same url.

**Comment by kof** [comment]
> Instead, I'd add a search field to filter quickly through the plugins.

Yeah, search would be nice, lets plan a space for it, won't implement it in the first iteration though.

**Comment by typical000** [comment]
> Can we try removing the dark background from the navigation and make it look more like the part of the content? Right now it stands out a lot but I don't think this is good.

> I still feel the yellow background for the logo is "too much"

Just tried to use white sidebar or without yellow background:
https://dl.dropboxusercontent.com/u/7605560/jss/menu_examples.png
Don't know. But, as for me, first and second menu design is better in any case.

**Comment by typical000** [comment]
> Move all baseStyles to the proper components

@kof already moved anchors styles in 'HighlightedMarkdown' component. Now in 'baseStyles' there are only typography styles, body styles, and svg tag styles.
We can move those styles to App only?

> Why REM?
It's just because I like to use REM and, in first version, I was planning to increase/decrease font sizes for different devices. But, after all, it was not needed :(
We can replace all with PX, but in this case we win only 'removing of jss.js utils file'

**Comment by kof** [comment]
I just think in the components world, they should not rely on global states, which rems represent in some way. Thats why I think rem is not a good fit, at least my opinion.

**Comment by okonet** [comment]
I think the 4th is great TBH! It looks clean and it also solves all issues with the logo — it's just the logo :)

I still feel we should remove the stars and github link to the home content area. 

As for the selected navigation state: can you try something more prominent with the 4th variant please?

**Comment by kof** [comment]
Looks like most people liked the second on twitter https://twitter.com/oleg008/status/816241839518969857

**Comment by okonet** [comment]
That's because you didn't show the full picture. It's hard to make a right impression with the cut. Try showing full mockups of 2 and 4 in another poll. I bet 4 will win then :)

**Comment by typical000** [comment]
Added design for contributors page - https://dl.dropboxusercontent.com/u/7605560/jss/design_contributors.jpg

PS: Sorry for using real photos and real info :)

**Comment by kof** [comment]
Maybe, @typical000 can you prepare 2 screenshots which show full picture?

**Comment by typical000** [comment]
Sure!
https://dl.dropboxusercontent.com/u/7605560/jss/last_examples.png

**Comment by kof** [comment]
@okonet should we make a vote on this two? You think they are fine as they are on that screen?

**Comment by typical000** [comment]
But if use light sidebar - promo block looks ugly  https://dl.dropboxusercontent.com/u/7605560/jss/design_white.jpg

**Comment by okonet** [comment]
I think we should remove this promo block. 

@kof I think they are fine. I wouldn't vote and would just go with the light one since it's much more calmer and legible one. But it's for your to decide.

**Comment by kof** [comment]
https://twitter.com/oleg008/status/816756090977271810

More people like the dark nav. I could make a real poll because twitter allows only text in polls. When you count also count the likes for each choice.

I would go for the dark one also because its already done, the other theme needs to be implemented. Also I think we should have both themes, maybe with a switch.

**Comment by okonet** [comment]
I wouldn't bother implementing 2 themes besides as an example of how awesome JSS is.

**Comment by kof** [comment]
Yeah, dynamic theme switch at runtime without reload is actually a big pro for cssinjs.

**Comment by okonet** [comment]
BTW its 50/50 what people prefer if you count my voice for the light one :)

But you should decide as a maintainer and author of JSS meaning for now it's more about someones preference since both designs are solid.

**Comment by kof** [comment]
We are ready to release it at least from what we know: http://cssinjs.org/

I am gathering feedbacks now, before we announce it.

**Comment by kof** [comment]
Feedbacks:

- [ ] Promo screen is annoying
- [ ] Promo on IP6 is too big (edges are cut)
- [ ] Auto numbered list broken http://cssinjs.org/benefits
- [ ] When version select loads during transition, jumps are visible
- [ ] Headline anchor vertical alignment
- [ ] Save scroll position when navigating back/forward
- [ ] Examples links to plugins should lead to the specific plugin example, not the overview
- [ ] Find better position on plugin documentation pages for "Demo" link
- [ ] Add "View on Github" button to all examples
- [ ] Remove link to old examples overview from jss/readme
- [ ] Scroll to the anchor on reload

**Comment by kof** [comment]
closing it now

**Comment by kof** [comment]
All known issues done http://cssinjs.org/ feel free to test everybody.
