### ISSUE TITLE
Remove JSON.stringify/parse, add onProcessStyle hook and more.

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#444]
This will strongly improve performance and fix #441.
Instead of JSON.stringify/parse of the style object in `Rule` we will shallow clone rule.style. According to my tests it will be still much faster than it currently is with stringify/parse.

## Todo
- [x] Add new hook `onProcessStyle(style, rule, sheet)` which will behave like an [].map
    - only for rules which have a style object
    - replaces `rule.style` object with the result from `onProcessStyle()`
- [x] Introduce `jss.cloneStyle(style)` utility fn for high perf cloning
    - Deep clone
    - Iterate over object without hasOwnProperty check, because we expect plain objects
    ```
    // Prototype
    function cloneStyle(style) {
      const newStyle = Object.create(null)
      for (const name in style) {
        newStyle[name] = style[name]
      }
      return newStyle
    }
    ```    
- [x] use cloneStyle in the Rule
- [x] Remove JSON.parse/stringify, check the bench
- [x] Breaking change for `generateClassName(styleStr)` - we have no string any more.
- [x] Remove rule.originalStyle - we can get the original style from the sheet, doesn't need to be RegularRule property.
- [x] Remove default hook mapping
- [x] update all plugins which only change/generate style object to use the new hook (like jss-camel-case or jss-extend)
- [x] update all plugins use new api for originalStyle
- [x] update all plugins with the new generateClassName signature

**Comment by kof** [comment]
cc @nathanmarks @cvle @iamstarkov

**Comment by kof** [comment]
I am about to copy/paste the deepFreezeAndThrowOnMutationInDev function from the react-native package. Does any one know a better alternative? I think adding react-native to dependencies is a huge dependency overhead just for this case.

**Comment by kof** [comment]
cc @cssinjs/core

**Comment by kof** [comment]
Alternatively I could use cloning and diffing in order to warn about mutation, because `deepFreezeAndThrowOnMutationInDev` has those caveats: 

```
 * There are two caveats with this function:
 *   - If the call site is not in strict mode, it will only throw when
 *     mutating existing fields, adding a new one
 *     will unfortunately fail silently :(
 *   - If the object is already frozen or sealed, it will not continue the
 *     deep traversal and will leave leaf nodes unfrozen.
```

**Comment by kof** [comment]
I think we don't need `onProcessRule(rule, sheet)` hook any more and we should use `onProcessStyle(style, rule, sheet)` for everything, style changes and rule/sheet manipulations. Just for the sake of not having too much hooks.

@cssinjs/core wdyt?

**Comment by iamstarkov** [comment]
@kof I don't know. But smaller API surface seems to be nice

**Comment by kof** [comment]
Fixed, check out jss 7.0
