### ISSUE TITLE
[jss-observable] [jss-function] Move function values and observable values to a plugin in a separate repository

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#700]
I think we should move them, because too many people are not using them, so it would reduce bundle size for them. It will still stay in jss-preset-default, so for all people who use them, it won't be a change.

## Todo
- [x] extract observables into sep package
- [x] extract function values and rules into sep package
- [x] add them to jss-preset- default
- [x] remove them from the core

**Comment by kof** [comment]
@cssinjs/core I am gonna do this now, since we have mono repo and separating packages is cheap. Biggest benefit is bundle size reduction for those who don't use functional dsl nor observables for e.g. mui cc @oliviertassinari

**Comment by kof** [comment]
Also @cssinjs/core do you think jss-observable and jss-functions are good names?

**Comment by HenriBeck** [comment]
I think `jss-observable` is fine. Don't know about `jss-function` though, as it's a bit misleading in my opinion. What about `jss-function-values`?

**Comment by kof** [comment]
I [started](https://github.com/cssinjs/jss/pull/749) to extract jss-observable, but realized many things are not ready where @HenriBeck is working on.

Mb its better for @HenriBeck to take over this one and start with these 2 plugins, before continuing with the other since we have an important benefit from doing these 2 first.

**Comment by oliviertassinari** [comment]
Can't wait to see this story completed :)!

**Comment by HenriBeck** [comment]
will work on it after I resolved the issues with rollup in #748

**Comment by kof** [comment]
I don' like jss-function name either, butthe thing is it is both, fn rules and fn values. Mb jss-function-value-and-rule

**Comment by HenriBeck** [comment]
Hmmm... yeah. Maybe `jss-function-plugin` and `jss-observable-plugin`?

**Comment by kof** [comment]
That would be inconsistent and still doesn't tell that its about the jss
syntax

**Comment by kof** [comment]
What about jss-function-syntax ? Still a bit inconsistant with other
syntactic plugins, but at least less confusing regarding "plugin"

I made a mistake of not prefixing all plugins with "plugin" eg
jss-plugin-xxx ... mb its time to change that.

**Comment by HenriBeck** [comment]
As the observable plugin has been moved out of jss, I will start working on the function rules plugin.

`jss-function-syntax` seems to be a good name. Then `jss-observable-syntax` aswell?

**Comment by kof** [comment]
I checked babel naming convention, they have this: babel-plugin-syntax-{something}, I think we should start doing this for syntactic stuff

**Comment by kof** [comment]
jss-plugin-syntax-function and jss-plugin-syntax-observable

**Comment by kof** [comment]
wait, since we wanted to have functions as a value in some other cases as well, for e.g. jss-compose and jss-extend, this will become even more unclear, since functions in those are not part of this plugin.

I think we have to become even more explicit: "jss-plugin-syntax-rule-value-function"
For e.g. see "babel-plugin-syntax-object-rest-spread"

**Comment by HenriBeck** [comment]
Okay, so we change the names of the other plugins as well then?

**Comment by kof** [comment]
Yeah, I think we should do this now, since we are making a big change anyways.

**Comment by kof** [comment]
Dunno if this means we have to increase a major version, I think we don't since its a new package and we can start it whereever we want.

**Comment by kof** [comment]
and jss-plugin-syntax-rule-value-observable

**Comment by HenriBeck** [comment]
I think we should because we definitely need to increase the major version of jss. And having all of the packages on the same version at all times is a good idea, I think.

Will change the observable package name then.

**Comment by kof** [comment]
Why would you need to increase major of jss, do we have any breaking changes?

**Comment by HenriBeck** [comment]
Yeah, removing the function and observable plugin?

**Comment by kof** [comment]
Oh, sorry, I forgot, we moved away those plugins, it is definitely breaking change for the core.

**Comment by HenriBeck** [comment]
So we could just publish all of the plugins with version 10.0.0

**Comment by kof** [comment]
yep

**Comment by kof** [comment]
Should we close this one?

**Comment by HenriBeck** [comment]
yes, I think we can close this
