### ISSUE TITLE
Migrate to Jest

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#745]
## Todo

- [ ] Extract CSSOM/DOM utilities https://github.com/cssinjs/jss/issues/744
- [ ] Migrate react-jss tests 
- [ ] Migrate each other package that gets into the monorepo

**Comment by HenriBeck** [comment]
The most significant difference is that jest doesn't use `it` and instead uses `test` which should be a simple search and replace for migrating most of the tests

**Comment by TrySound** [comment]
@HenriBeck Actually it has all `describe`, `it`, `test`.

**Comment by TrySound** [comment]
Rewire conversion is messy. I did it, but can't figure out how to run karma with babel7 for functional tests.

**Comment by HenriBeck** [comment]
We could remove rewire when we switch to jest mocking libary.

**Comment by TrySound** [comment]
I removed and switched. We just need to move out functional tests somewhere and I will push jest tests.
