### ISSUE TITLE
v10 release roadmap

### ISSUE THREAD

**Issue by HenriBeck** [cssinjs/jss#795]
Just wanted to write some things down which we need to do before the release:

- [x] Add typings to the extend plugin and preset default
- [x] Enable babel loose mode #792 
- [x] [[react-jss] prepare for react 17 (but maintain backward compat)](https://github.com/cssinjs/jss/issues/802)
- [x] [[react-jss] Add flowtype support](https://github.com/cssinjs/jss/issues/797)
- [x] Migrate to monorepo #714
- [x] Migrate to yarn and workspaces
- [x] [[react-jss] Drop support for react 0.13 and 0.14](https://github.com/cssinjs/jss/issues/836)
- [x] Support full syntax in fn values #682
- [x] Support Houdini Typed OM #882 
- [x] Generate keyframe ids #346
- [ ] Docs #932
- [x] Update [cssinjs](http://cssinjs.org) website
- [x] Update REPL

**Comment by TrySound** [comment]
Okay, what is left?

- [[react-jss] Drop support for react 0.13 and 0.14](https://github.com/cssinjs/jss/issues/836)
- [[react-jss] prepare for react 17 (but maintain backward compat)](https://github.com/cssinjs/jss/issues/802)
- [[react-jss] Readd forwardRef support](https://github.com/cssinjs/jss/issues/800)
- [[react-jss] Add flowtype support](https://github.com/cssinjs/jss/issues/797)

**Comment by HenriBeck** [comment]
We can't add forwardRef support because of `redux`. We will need to wait until they push a fix.

Dropping support for react 0.13 and 0.14 should be relatively easy. The new context implementation could come later, we should just drop the versions on the major release.

**Comment by kof** [comment]
Updated the roadmap, we discussed with @HenriBeck today that it would be good to include #346 and #682 into that release. They are not very hard to get done and both involve breaking changes.

**Comment by kof** [comment]
We released an alpha v10

**Comment by kof** [comment]
Released  v10 stable, not all goals were met, but I am closing this issue anyways, we need a new roadmap for v11.
