### ISSUE TITLE
Use WeakMap

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#880]
We are using in many cases a generated property directly on an object/function when we need to associate a value with that object. I think WeakMap support is hight enough now that we can start using it and assume people will include a WeakMap polyfill for older browsers.

I think React is also using WeakMap.

## Todo
- [ ] use it in plugin-syntax-rule-value-function
- [ ] use it in plugin-cache
- [ ] update docs which refer required polyfils
- [ ] search where else it could be used

**Comment by HenriBeck** [comment]
👍

**Comment by HenriBeck** [comment]
WeakMap can't be used inside plugin-syntax-rule-value-function because a WeakMap needs objects as keys.

**Comment by kof** [comment]
Function is an object, can be used as a key

**Comment by HenriBeck** [comment]
Ohh yeah, so the function would be the keys and the actual css prop name would be the value in the WeakMap

**Comment by kof** [comment]
@HenriBeck I think we can close this one, no?

**Comment by HenriBeck** [comment]
No, not yet, we haven't converted the function plugin to use it.
