### ISSUE TITLE
Make sure styled-system is supported

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#974]
Styled-System by @jxnblk https://github.com/jxnblk/styled-system seems like a  very solid approach for building design systems. I think we should look into it and see how it can be supported. 

## Todo

- [ ] See how it can be supported 
- [ ] Add it to documentation with links
- [ ] Make codesandbox examples
- [ ] Send a PR to styled-system and link the examples

**Comment by jxnblk** [comment]
Haven't really tested it recently, but styled-system *should* "just work" with `styled-jss`. Definitely let me know if you run into any bugs though

**Comment by kof** [comment]
I wonder if it also can work with react-jss and the future version of it based on hooks (prototype https://github.com/cssinjs/react-jss-hook)

**Comment by HenriBeck** [comment]
It should already work with react-jss

**Comment by Eddort** [comment]
this only works with react-jss @ alpha-10
but if you want to use something like `<Box p = {[1, 1/2, 1/4]}> </ Box>` you will notice a bug [#1044](https://github.com/cssinjs/jss/issues/1044)

**Comment by kof** [comment]
Putting high prio on that bug.

**Comment by HenriBeck** [comment]
I think the issue is that `styled-system` is accessing the theme via props and not from our `themed styles` function.

**Comment by kevinSuttle** [comment]
Would love to see this also.

**Comment by kof** [comment]
@jxnblk do you see a good way to support styled-system without enforcing use of components, but with functions instead?

**Comment by kevinSuttle** [comment]
What is the relationship between https://material-ui.com/system/basics/ and JSS here?

**Comment by kof** [comment]
MUI style system is an independent effort by @oliviertassinari inspired by styled-system. It is a separate package https://github.com/mui-org/material-ui/tree/next/packages/material-ui-system and seems to have no direct dependency on JSS, but can be used together.

I am also porting an SC-like, similar to styled-jss into the react-jss package to support styled-system and SC-pattern users.

**Comment by kevinSuttle** [comment]
See also: https://github.com/emotion-js/emotion/tree/master/packages/primitives-core

**Comment by kof** [comment]
@kevinSuttle what specific use case from primitive-core are you interested in?

**Comment by kevinSuttle** [comment]
Nothing in particular. It's just another approach—one that isn't included in the Prior Art section here: https://material-ui.com/system/basics/#prior-art

Also odd that `styled-system` isn't mentioned here.

**Comment by kof** [comment]
it is mentioned there)

**Comment by kevinSuttle** [comment]
(Edited)

**Comment by kof** [comment]
Turns out styled system doesn't depend on SC pattern at all, those are just functions. I was confused by the fact they expose propTypes, so I thought they must be rendered as components, but actually those propTypes need to be merged into user component manually if you want the warnings.

The only thing that is actually special about styled system is the data structure in which it returns the styles:

```json
[
  [
    {
      "paddingLeft": "4px"
    }
  ],
  [
    {
      "paddingRight": "4px"
    }
  ]
]
```

**Comment by kof** [comment]
Turns out v3 of styled-system just works without any extra code, the only thing one needs to do is to set  `injectTheme` to `true`:

```js
    const styles = {
      root: compose(
        space,
        color,
        fontSize,
        width,
        fontWeight,
        lineHeight
      )
    }

    const MyComponent = ({classes}) => <div className={classes.root} />

    const MyStyledComponent = withStyles(styles, {injectTheme: true})(MyComponent)

    const renderer = TestRenderer.create(
      <ThemeProvider theme={theme}>
        <MyStyledComponent
          px={[3, 4]}
          py={[1, 2]}
          color="white"
          bg="blue"
          fontSize={[4, 5, 6]}
          fontWeight="bold"
        />
      </ThemeProvider>
    )
```

**Comment by jxnblk** [comment]
@kof Heads up: I've started a PR here: https://github.com/styled-system/styled-system/pull/473 and it's now published as `styled-system@4.2.0-0` if you'd like to test it out

**Comment by kevinSuttle** [comment]
How does that affect performance?

**Comment by kof** [comment]
@jxnblk nice, gonna try it out in a bit

**Comment by jxnblk** [comment]
@kevinSuttle the babel plugin package is *experimental* and does not use the same code base as Styled System core

**Comment by kof** [comment]
@jxnblk I confirm styled-system@4.2.0-0 works with my tests
